"NES": [
  { name: "Super Mario Bros.", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/03/Super_Mario_Bros._box.png" },
  { name: "The Legend of Zelda", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0d/Legend_of_Zelda_NES_box.png" },
  { name: "Metroid", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0c/Metroid_NES_box.jpg" },
  { name: "Mega Man 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/55/Mega_Man_2_cover.png" },
  { name: "Castlevania", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/4f/Castlevania_NES.jpg" },
  { name: "Mike Tyson’s Punch-Out!!", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/9/9f/Punch-OutNES.png" },
  { name: "Duck Hunt", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/b/bc/Duck_Hunt_box_art.jpg" },
  { name: "Contra", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e7/Contra_NES_box_art.jpg" },
  { name: "Punch-Out!! Featuring Mr. Dream", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Excitebike", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/73/Excitebike.png" },
  { name: "Kid Icarus", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/27/KidIcarus.png" },
  { name: "Dragon Warrior", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Final Fantasy", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Tecmo Bowl", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Bubble Bobble", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6b/BubbleBobbleNES.png" },
  { name: "Bionic Commando", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Ninja Gaiden", owned: false, img: "https://via.placeholder.com/100" },
  { name: "River City Ransom", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Super C", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Blaster Master", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Tecmo Super Bowl", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Double Dragon II", owned: false, img: "https://via.placeholder.com/100" },
  { name: "The Adventures of Link", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Kirby’s Adventure", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Dr. Mario", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5e/Dr._Mario_box_art.png" },
  { name: "Super Mario Bros. 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5b/Super_Mario_Bros_2_box.png" },
  { name: "Super Mario Bros. 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2d/Super_Mario_Bros._3.png" },
  { name: "Zelda II: The Adventure of Link", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/53/Adventure_of_Link_box_art.png" },
  { name: "Track & Field", owned: false, img: "https://via.placeholder.com/100" }
],
"Game Boy": [
  { name: "Tetris", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/57/Tetris_GameBoy.jpg" },
  { name: "Pokemon Red", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/32/Pokemon_Red_Version.jpg" },
  { name: "Pokemon Blue", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/27/Pokemon_Blue_Version_box_art.jpg" },
  { name: "The Legend of Zelda: Link's Awakening", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e5/Zelda_Link%27s_Awakening_cover.jpg" },
  { name: "Super Mario Land", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3d/Super_Mario_Land_Box_Art.png" },
  { name: "Donkey Kong", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/55/Donkey_Kong_Box_Art.png" },
  { name: "Kirby's Dream Land", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d6/Kirby%27s_Dream_Land_cover_art.jpg" },
  { name: "Dr. Mario", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5e/Dr._Mario_box_art.png" },
  { name: "Metroid II: Return of Samus", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Castlevania: The Adventure", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Final Fantasy Adventure", owned: false, img: "https://via.placeholder.com/100" },
  { name: "R-Type", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Mega Man: Dr. Wily's Revenge", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Kirby's Pinball Land", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Super Mario Land 2: 6 Golden Coins", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/64/Super_Mario_Land_2_cover.jpg" },
  { name: "Donkey Kong Land", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Pokemon Yellow", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/15/Pokemon_Yellow_Boxart.png" },
  { name: "Wario Land: Super Mario Land 3", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Ninja Gaiden Shadow", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Double Dragon", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Balloon Kid", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Solar Striker", owned: false, img: "https://via.placeholder.com/100" },
  { name: "F1 Race", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Blaster Master Boy", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Tetris Attack", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Mickey's Dangerous Chase", owned: false, img: "https://via.placeholder.com/100" },
  { name: "RoboCop", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Teenage Mutant Ninja Turtles: Fall of the Foot Clan", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Dragon Warrior Monsters", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Final Fantasy Legend", owned: false, img: "https://via.placeholder.com/100" }
],
"GBA": [
  { name: "Pokemon Ruby", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6d/Pokemon_Ruby.jpg" },
  { name: "Pokemon Sapphire", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/9/96/Pokemon_Sapphire.jpg" },
  { name: "Pokemon FireRed", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/b/bd/Pokemon_FireRed_Box.jpg" },
  { name: "Pokemon LeafGreen", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/37/Pokemon_LeafGreen_Box.png" },
  { name: "The Legend of Zelda: The Minish Cap", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2c/Zelda_Minish_Cap_Box.png" },
  { name: "Advance Wars", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/79/Advance_Wars_Coverart.png" },
  { name: "Metroid Fusion", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/9/99/Metroid_Fusion_Boxart.jpg" },
  { name: "Metroid: Zero Mission", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/55/Metroid_Zero_Mission_Boxart.jpg" },
  { name: "Fire Emblem", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d3/Fire_Emblem_GBA_cover.jpg" },
  { name: "Mario Kart: Super Circuit", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e8/Mario_Kart_Super_Circuit_boxart.png" },
  { name: "Super Mario Advance", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/15/Super_Mario_Advance_box.png" },
  { name: "Super Mario Advance 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7f/Super_Mario_Advance_2_box.png" },
  { name: "Super Mario Advance 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/48/Super_Mario_Advance_3_Box.png" },
  { name: "Super Mario Advance 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/8f/Super_Mario_Advance_4_Box.png" },
  { name: "Castlevania: Aria of Sorrow", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3f/Castlevania_Aria_of_Sorrow_Box.png" },
  { name: "Castlevania: Harmony of Dissonance", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Castlevania: Circle of the Moon", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Golden Sun", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6e/Golden_Sun_Box.png" },
  { name: "Golden Sun: The Lost Age", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f5/Golden_Sun_The_Lost_Age_Box.png" },
  { name: "Mario & Luigi: Superstar Saga", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f3/Mario_and_Luigi_Superstar_Saga_boxart.jpg" },
  { name: "Kirby: Nightmare in Dream Land", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f3/Kirby_Nightmare_in_Dream_Land_Box.png" },
  { name: "Pokemon Mystery Dungeon: Red Rescue Team", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/27/Pokemon_Mystery_Dungeon_Red_Rescue_Team_Box.jpg" },
  { name: "Final Fantasy Tactics Advance", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/48/Final_Fantasy_Tactics_Advance_Box.png" },
  { name: "Wario Land 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fb/Wario_Land_4_Box.png" },
  { name: "F-Zero: Maximum Velocity", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/36/F-Zero_Maximum_Velocity_Box.png" },
  { name: "Mario Party Advance", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Donkey Kong Country", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Donkey Kong Country 2", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Donkey Kong Country 3", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Mega Man Zero", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3b/Mega_Man_Zero_Box.png" }
],
"Sega Mega Drive": [
  { name: "Sonic the Hedgehog", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/37/Sonic_the_Hedgehog_MD_box_art.png" },
  { name: "Sonic the Hedgehog 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f7/Sonic_the_Hedgehog_2_box_art.png" },
  { name: "Sonic the Hedgehog 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6b/Sonic_3_MD_Box.png" },
  { name: "Sonic & Knuckles", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5f/Sonic_%26_Knuckles_Box.png" },
  { name: "Streets of Rage", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5f/Streets_of_Rage_Box.jpg" },
  { name: "Streets of Rage 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/9/9d/Streets_of_Rage_2_box_art.png" },
  { name: "Golden Axe", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/ee/Golden_Axe_MD_cover.jpg" },
  { name: "Golden Axe II", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Altered Beast", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f4/Altered_Beast_MD_Box.jpg" },
  { name: "Shining Force", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/12/Shining_Force_MD_Box.png" },
  { name: "Shining Force II", owned: false, img: "https://via.placeholder.com/100" },
  { name: "ToeJam & Earl", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/61/ToeJam_Earl_Box.jpg" },
  { name: "Earthworm Jim", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fd/Earthworm_Jim_MD_box.png" },
  { name: "Gunstar Heroes", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/75/Gunstar_Heroes_MD_cover.png" },
  { name: "Comix Zone", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Ecco the Dolphin", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/78/Ecco_the_Dolphin_Box.jpg" },
  { name: "Ecco: The Tides of Time", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Phantasy Star II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d6/Phantasy_Star_II_MD_cover.jpg" },
  { name: "Phantasy Star III", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Phantasy Star IV", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Aladdin", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/63/Aladdin_MD_box.png" },
  { name: "Disney's The Lion King", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f1/The_Lion_King_MD_box.jpg" },
  { name: "Road Rash", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/c1/Road_Rash_MD_box.png" },
  { name: "Road Rash II", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Columns", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/61/Columns_MD_box.jpg" },
  { name: "Ristar", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2f/Ristar_MD_Box.png" },
  { name: "ToeJam & Earl in Panic on Funkotron", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Wonder Boy in Monster World", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Virtua Fighter 2", owned: false, img: "https://via.placeholder.com/100" },
  { name: "NBA Jam", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/ea/NBA_Jam_MD_cover.png" }
],
"N64": [
  { name: "Super Mario 64", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/46/Super_Mario_64_box.png" },
  { name: "The Legend of Zelda: Ocarina of Time", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7e/Zelda_Ocarina_of_Time.png" },
  { name: "The Legend of Zelda: Majora's Mask", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f5/Zelda_Majoras_Mask_cover.jpg" },
  { name: "Mario Kart 64", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3e/Mario_Kart_64_box.jpg" },
  { name: "GoldenEye 007", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fd/GoldenEye_007_cover.jpg" },
  { name: "Super Smash Bros.", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/57/Smash64cover.jpg" },
  { name: "Banjo-Kazooie", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d2/Banjo-Kazooie_cover.png" },
  { name: "Banjo-Tooie", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Donkey Kong 64", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/74/Donkey_Kong_64_cover.jpg" },
  { name: "Star Fox 64", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d4/Star_Fox_64_box.jpg" },
  { name: "Wave Race 64", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/52/Wave_Race_64_cover.png" },
  { name: "F-Zero X", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fb/F-Zero_X_N64_cover.jpg" },
  { name: "Pokémon Stadium", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3e/Pokemon_Stadium_cover.jpg" },
  { name: "Pokémon Stadium 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3b/Pokemon_Stadium_2_cover.jpg" },
  { name: "Paper Mario", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/69/Paper_Mario_N64_box.png" },
  { name: "Mario Party", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0f/MarioParty_box.png" },
  { name: "Mario Party 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f0/MarioParty2_cover.jpg" },
  { name: "Mario Party 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e5/MarioParty3_box.jpg" },
  { name: "Yoshi's Story", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e0/Yoshi%27s_Story_N64_cover.png" },
  { name: "Pilotwings 64", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0d/Pilotwings64.png" },
  { name: "Resident Evil 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/31/Resident_Evil_2_N64_cover.jpg" },
  { name: "Castlevania 64", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Diddy Kong Racing", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d1/Diddy_Kong_Racing_Box.png" },
  { name: "Turok: Dinosaur Hunter", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/c2/Turok_cover.jpg" },
  { name: "Turok 2: Seeds of Evil", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Excitebike 64", owned: false, img: "https://via.placeholder.com/100" },
  { name: "1080° Snowboarding", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fc/1080_Snowboarding_box.jpg" },
  { name: "Killer Instinct Gold", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Mischief Makers", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/66/Mischief_Makers_N64.jpg" },
  { name: "Excitebike 64", owned: false, img: "https://via.placeholder.com/100" }
],
"GameCube": [
  { name: "Super Smash Bros. Melee", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/b/b2/SSBMcover.jpg" },
  { name: "The Legend of Zelda: The Wind Waker", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/43/Zelda_Wind_Waker_Box.png" },
  { name: "Metroid Prime", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e4/Metroid_Prime_cover.jpg" },
  { name: "Metroid Prime 2: Echoes", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/1b/Metroid_Prime_2_Echoes_cover.jpg" },
  { name: "Mario Kart: Double Dash!!", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6a/Mario_Kart_Double_Dash_box.jpg" },
  { name: "Luigi's Mansion", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/65/Luigi%27s_Mansion_Box.png" },
  { name: "Super Mario Sunshine", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/df/Super_Mario_Sunshine_box.png" },
  { name: "Resident Evil 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2e/Resident_Evil_4_GameCube_boxart.jpg" },
  { name: "Paper Mario: The Thousand-Year Door", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/1d/Paper_Mario_TTYD_Box.png" },
  { name: "F-Zero GX", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/85/F-Zero_GX_Box.png" },
  { name: "Pikmin", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/36/Pikmin_box.jpg" },
  { name: "Pikmin 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/66/Pikmin_2_box.jpg" },
  { name: "Fire Emblem: Path of Radiance", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/64/Fire_Emblem_Path_of_Radiance_cover.jpg" },
  { name: "Animal Crossing", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/Animal_Crossing_GameCube_cover.png" },
  { name: "Donkey Kong Jungle Beat", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/29/Donkey_Kong_Jungle_Beat_box.png" },
  { name: "Mario Party 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/86/Mario_Party_4_box.jpg" },
  { name: "Mario Party 5", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/63/Mario_Party_5_box.jpg" },
  { name: "Mario Party 6", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/4f/Mario_Party_6_cover.jpg" },
  { name: "Mario Party 7", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5e/Mario_Party_7_cover.jpg" },
  { name: "Super Mario Strikers", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7b/Super_Mario_Strikers_box.jpg" },
  { name: "Soulcalibur II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0f/Soulcalibur_II_box.jpg" },
  { name: "Resident Evil", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7c/Resident_Evil_GameCube.jpg" },
  { name: "Resident Evil 0", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/de/Resident_Evil_0_GameCube.jpg" },
  { name: "Eternal Darkness: Sanity's Requiem", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/12/Eternal_Darkness_Box.png" },
  { name: "Viewtiful Joe", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0f/Viewtiful_Joe_box.png" },
  { name: "Super Smash Bros. Melee", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/b/b2/SSBMcover.jpg" },
  { name: "Super Monkey Ball", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/41/Super_Monkey_Ball_cover.png" },
  { name: "Super Monkey Ball 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6e/Super_Monkey_Ball_2_cover.png" },
  { name: "Luigi's Mansion", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/65/Luigi%27s_Mansion_Box.png" },
  { name: "F-Zero GX", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/85/F-Zero_GX_Box.png" }
],
"PS1": [
  { name: "Final Fantasy VII", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6b/Final_Fantasy_VII_Boxart.jpg" },
  { name: "Final Fantasy VIII", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/51/Final_Fantasy_VIII_Boxart.jpg" },
  { name: "Final Fantasy IX", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6f/Final_Fantasy_IX_boxart.jpg" },
  { name: "Metal Gear Solid", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/8b/Metal_Gear_Solid_cover.jpg" },
  { name: "Resident Evil", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7c/Resident_Evil_PS1.jpg" },
  { name: "Resident Evil 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/17/Resident_Evil_2_PS1_cover.jpg" },
  { name: "Gran Turismo", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/49/Gran_Turismo_Cover_Art.jpg" },
  { name: "Gran Turismo 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f7/Gran_Turismo_2_box.jpg" },
  { name: "Crash Bandicoot", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/74/Crash_Bandicoot_cover.jpg" },
  { name: "Crash Bandicoot 2: Cortex Strikes Back", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/88/Crash_Bandicoot_2_cover.jpg" },
  { name: "Crash Bandicoot 3: Warped", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/49/Crash_Bandicoot_3_cover.jpg" },
  { name: "Spyro the Dragon", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/44/Spyro_the_Dragon_cover.jpg" },
  { name: "Spyro 2: Ripto's Rage!", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/62/Spyro_2_cover.jpg" },
  { name: "Spyro: Year of the Dragon", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/56/Spyro_3_cover.jpg" },
  { name: "Castlevania: Symphony of the Night", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f1/Castlevania_SOTN_cover.jpg" },
  { name: "Tomb Raider", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2c/Tomb_Raider_cover_art.png" },
  { name: "Tomb Raider II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/c5/Tomb_Raider_II_cover.png" },
  { name: "Tomb Raider III", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/dc/Tomb_Raider_III_cover.png" },
  { name: "Tony Hawk's Pro Skater", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/cb/Tony_Hawk%27s_Pro_Skater_cover.jpg" },
  { name: "Tony Hawk's Pro Skater 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fb/Tony_Hawk%27s_Pro_Skater_2_cover.jpg" },
  { name: "Resident Evil 3: Nemesis", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3f/Resident_Evil_3_Nemesis_Cover.png" },
  { name: "Silent Hill", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f4/Silent_Hill_PS1_box.jpg" },
  { name: "Vagrant Story", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e8/Vagrant_Story_box.jpg" },
  { name: "Parappa the Rapper", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fc/PaRappa_the_Rapper_cover.jpg" },
  { name: "Driver", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d6/Driver_PS1_Cover.jpg" },
  { name: "Resident Evil: Director's Cut", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7c/Resident_Evil_PS1.jpg" },
  { name: "Twisted Metal", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/19/Twisted_Metal_cover.jpg" },
  { name: "Twisted Metal 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2b/Twisted_Metal_2_cover.jpg" },
  { name: "Oddworld: Abe's Oddysee", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/ed/Oddworld_Abes_Oddysee_cover.jpg" },
  { name: "Gran Turismo", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/49/Gran_Turismo_Cover_Art.jpg" }
],
"PS2": [
  { name: "Grand Theft Auto: San Andreas", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/44/GTA_San_Andreas_box_art.jpg" },
  { name: "Grand Theft Auto: Vice City", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/9/9f/GTA_VC_box_art.jpg" },
  { name: "Grand Theft Auto III", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/4f/GTA_III_cover.png" },
  { name: "Final Fantasy X", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/66/Final_Fantasy_X_cover_art.jpg" },
  { name: "Final Fantasy XII", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/8d/Final_Fantasy_XII_box.jpg" },
  { name: "Metal Gear Solid 2: Sons of Liberty", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/30/MGS2cover.jpg" },
  { name: "Metal Gear Solid 3: Snake Eater", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/MGS3box.jpg" },
  { name: "Kingdom Hearts", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7c/KingdomHeartsbox.jpg" },
  { name: "Kingdom Hearts II", owned: false, img: "https://via.placeholder.com/100" },
  { name: "God of War", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e2/God_of_War_PS2_cover.png" },
  { name: "God of War II", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Shadow of the Colossus", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5c/Shadow_of_the_Colossus_cover_art.jpg" },
  { name: "ICO", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/36/Ico_cover.png" },
  { name: "Devil May Cry", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5a/Devil_May_Cry_cover.jpg" },
  { name: "Devil May Cry 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2f/Devil_May_Cry_3_Box.png" },
  { name: "Resident Evil 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2e/Resident_Evil_4_GameCube_boxart.jpg" },
  { name: "Resident Evil Code: Veronica X", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/18/Resident_Evil_Code_Veronica_X_cover.jpg" },
  { name: "Silent Hill 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/80/Silent_Hill_2_cover.jpg" },
  { name: "Silent Hill 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5b/Silent_Hill_3_cover.jpg" },
  { name: "Gran Turismo 3: A-Spec", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/61/GT3ASpec.jpg" },
  { name: "Gran Turismo 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5c/GT4box.jpg" },
  { name: "Final Fantasy X-2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/41/FFX-2_box.jpg" },
  { name: "Dragon Quest VIII", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/03/Dragon_Quest_VIII_cover.jpg" },
  { name: "Kingdom Hearts: Chain of Memories", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Jak and Daxter: The Precursor Legacy", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fd/Jak_and_Daxter_Box.png" },
  { name: "Jak II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2c/Jak2cover.jpg" },
  { name: "Ratchet & Clank", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7e/RatchetAndClankCover.jpg" },
  { name: "Ratchet & Clank: Going Commando", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5c/RatchetAndClankGCover.jpg" },
  { name: "Jak 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/81/Jak_3_cover.jpg" },
  { name: "ICO & Shadow of the Colossus Collection", owned: false, img: "https://via.placeholder.com/100" }
],
"PS3": [
  { name: "The Last of Us", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fb/The_Last_of_Us_cover.jpg" },
  { name: "Uncharted: Drake's Fortune", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fd/Uncharted_Drake%27s_Fortune.jpg" },
  { name: "Uncharted 2: Among Thieves", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d6/Uncharted_2_box.jpg" },
  { name: "Uncharted 3: Drake's Deception", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d3/Uncharted_3_cover.jpg" },
  { name: "God of War III", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/a/a0/God_of_War_III_cover.jpg" },
  { name: "God of War: Ascension", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f7/God_of_War_Ascension_cover.jpg" },
  { name: "Metal Gear Solid 4: Guns of the Patriots", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/c2/MGS4cover.jpg" },
  { name: "Heavy Rain", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/27/Heavy_Rain_cover.jpg" },
  { name: "Demon's Souls", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/41/Demons_Souls_cover.png" },
  { name: "LittleBigPlanet", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3e/LittleBigPlanet_Cover.jpg" },
  { name: "LittleBigPlanet 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f1/LittleBigPlanet2box.jpg" },
  { name: "Infamous", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/77/Infamous_Cover.jpg" },
  { name: "Infamous 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/86/Infamous2cover.jpg" },
  { name: "Killzone 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/Killzone2cover.jpg" },
  { name: "Killzone 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e8/Killzone3_cover.jpg" },
  { name: "Ratchet & Clank Future: Tools of Destruction", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/60/Ratchet_Clank_Tools_of_Destruction_cover.jpg" },
  { name: "Ratchet & Clank Future: A Crack in Time", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/18/Ratchet_Clank_A_Crack_in_Time.jpg" },
  { name: "Gran Turismo 5", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f0/Gran_Turismo_5_cover.jpg" },
  { name: "Gran Turismo 6", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/56/Gran_Turismo_6_cover.jpg" },
  { name: "FIFA 14", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/FIFA_14_cover_art.jpg" },
  { name: "FIFA 15", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f2/FIFA_15_cover.jpg" },
  { name: "NBA 2K14", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/36/NBA_2K14_cover.jpg" },
  { name: "NBA 2K15", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/80/NBA_2K15_cover.jpg" },
  { name: "Batman: Arkham Asylum", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/84/Batman_Arkham_Asylum_cover.jpg" },
  { name: "Batman: Arkham City", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f5/Batman_Arkham_City_cover.jpg" },
  { name: "Assassin's Creed II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0a/Assassins_Creed_II_cover.jpg" },
  { name: "Assassin's Creed III", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f8/Assassin%27s_Creed_III_cover.jpg" },
  { name: "Uncharted: Golden Abyss", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Journey", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/52/Journey_cover_art.jpg" },
  { name: "Ni no Kuni: Wrath of the White Witch", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0a/Ni_no_Kuni_Box_Art.jpg" }
],
"PSP": [
  { name: "God of War: Chains of Olympus", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fc/God_of_War_Chains_of_Olympus_cover.jpg" },
  { name: "God of War: Ghost of Sparta", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e6/God_of_War_Ghost_of_Sparta_cover.jpg" },
  { name: "Grand Theft Auto: Liberty City Stories", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/25/GTA_LCS_cover.jpg" },
  { name: "Grand Theft Auto: Vice City Stories", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/69/GTA_VCS_cover.jpg" },
  { name: "Monster Hunter Freedom Unite", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/66/Monster_Hunter_Freedom_Unite_cover.jpg" },
  { name: "Monster Hunter Portable 3rd", owned: false, img: "https://via.placeholder.com/100" },
  { name: "Metal Gear Solid: Peace Walker", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/16/Metal_Gear_Solid_Peace_Walker_cover.jpg" },
  { name: "Patapon", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/23/Patapon_cover.jpg" },
  { name: "Patapon 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/36/Patapon_2_cover.jpg" },
  { name: "Daxter", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3e/Daxter_cover.jpg" },
  { name: "Lumines", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0c/Lumines_Cover.png" },
  { name: "Crisis Core: Final Fantasy VII", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/19/Crisis_Core_FFVII_cover.jpg" },
  { name: "Final Fantasy Tactics: The War of the Lions", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/83/FFTTWotl_cover.jpg" },
  { name: "LittleBigPlanet", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3e/LittleBigPlanet_Cover.jpg" },
  { name: "SOCOM: U.S. Navy SEALs Fireteam Bravo", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0f/SOCOM_Fireteam_Bravo_cover.jpg" },
  { name: "SOCOM: U.S. Navy SEALs Fireteam Bravo 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/82/SOCOM_Fireteam_Bravo_2_cover.jpg" },
  { name: "Killzone: Liberation", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f6/Killzone_Liberation_cover.jpg" },
  { name: "Kingdom Hearts: Birth by Sleep", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/4d/Kingdom_Hearts_Birth_by_Sleep_cover.jpg" },
  { name: "Metal Gear Solid: Portable Ops", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3f/Metal_Gear_Solid_Portable_Ops_cover.jpg" },
  { name: "Resistance: Retribution", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/57/Resistance_Retribution_cover.jpg" },
  { name: "Tekken: Dark Resurrection", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/63/Tekken_Dark_Resurrection_cover.jpg" },
  { name: "Tekken 6", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e6/Tekken6_cover.jpg" },
  { name: "Dissidia: Final Fantasy", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0a/DissidiaFF_cover.jpg" },
  { name: "Dissidia 012 Final Fantasy", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/45/Dissidia_012_FF_cover.jpg" },
  { name: "MotorStorm: Arctic Edge", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0b/MotorStorm_Arctic_Edge_cover.jpg" },
  { name: "Ridge Racer", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/63/Ridge_Racer_PSP_cover.jpg" },
  { name: "Ridge Racer 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/09/Ridge_Racer_2_PSP_cover.jpg" },
  { name: "Syphon Filter: Dark Mirror", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2c/Syphon_Filter_Dark_Mirror_cover.jpg" },
  { name: "Syphon Filter: Logan's Shadow", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7c/Syphon_Filter_Logan%27s_Shadow_cover.jpg" },
  { name: "LocoRoco", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/cd/LocoRoco_cover.jpg" },
  { name: "LocoRoco 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/42/LocoRoco_2_cover.jpg" }
],
"Xbox 360": [
  { name: "Halo 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2f/Halo3box.jpg" },
  { name: "Halo: Reach", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/01/Halo_Reach_box.jpg" },
  { name: "Halo 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2f/Halo4_boxart.jpg" },
  { name: "Gears of War", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5a/Gears_of_War_box.jpg" },
  { name: "Gears of War 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0a/Gears_of_War_2_box.jpg" },
  { name: "Gears of War 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/ef/Gears_of_War_3_cover.jpg" },
  { name: "Fable II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0e/Fable_II_cover.jpg" },
  { name: "Fable III", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/55/Fable_III_box.jpg" },
  { name: "Mass Effect", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/52/Mass_Effect_cover.jpg" },
  { name: "Mass Effect 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/23/Mass_Effect_2_cover_art.jpg" },
  { name: "Mass Effect 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/b/b5/Mass_Effect_3_cover_art.jpg" },
  { name: "Assassin's Creed", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5d/AssassinsCreedbox.jpg" },
  { name: "Assassin's Creed II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0a/Assassins_Creed_II_cover.jpg" },
  { name: "Assassin's Creed III", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f8/Assassin%27s_Creed_III_cover.jpg" },
  { name: "Call of Duty 4: Modern Warfare", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3b/Call_of_Duty_4_box.jpg" },
  { name: "Call of Duty: Modern Warfare 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/21/Call_of_Duty_Modern_Warfare_2_cover.jpg" },
  { name: "Call of Duty: Modern Warfare 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2b/Call_of_Duty_Modern_Warfare_3_cover.jpg" },
  { name: "Call of Duty: Black Ops", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/57/Call_of_Duty_Black_Ops_box_art.jpg" },
  { name: "Call of Duty: Black Ops II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fb/Call_of_Duty_Black_Ops_II_box_art.jpg" },
  { name: "Forza Motorsport 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2b/Forza_Motorsport_2_cover.jpg" },
  { name: "Forza Motorsport 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3d/Forza_Motorsport_3_cover.jpg" },
  { name: "Forza Motorsport 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6d/Forza_Motorsport_4_cover.jpg" },
  { name: "Bioshock", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/25/BioShock_cover.jpg" },
  { name: "Bioshock 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/09/BioShock2box.jpg" },
  { name: "Bioshock Infinite", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3b/Bioshock_Infinite_box_art.jpg" },
  { name: "Batman: Arkham Asylum", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/84/Batman_Arkham_Asylum_cover.jpg" },
  { name: "Batman: Arkham City", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f5/Batman_Arkham_City_cover.jpg" },
  { name: "Dragon Age: Origins", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0c/Dragon_Age_Origins_cover.jpg" },
  { name: "Dragon Age II", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/15/Dragon_Age_II_cover.jpg" },
  { name: "The Elder Scrolls V: Skyrim", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6f/Skyrim_cover.png" },
  { name: "Dark Souls", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/5/5d/Dark_Souls_Cover_Art.jpg" }
],
"NES": [
  { name: "Super Mario Bros.", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/03/Super_Mario_Bros._box.png" },
  { name: "Super Mario Bros. 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/61/Super_Mario_Bros._2_box.png" },
  { name: "Super Mario Bros. 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/1b/Super_Mario_Bros_3_box.png" },
  { name: "The Legend of Zelda", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/9/9b/Legend_of_Zelda_Box.png" },
  { name: "Zelda II: The Adventure of Link", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/c6/Zelda_II_Box.png" },
  { name: "Metroid", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f7/Metroid_Box.png" },
  { name: "Mega Man", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/73/Mega_Man_Box.png" },
  { name: "Mega Man 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/28/Mega_Man_2_Box.png" },
  { name: "Mega Man 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/41/Mega_Man_3_Box.png" },
  { name: "Castlevania", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0d/Castlevania_NES_Box.png" },
  { name: "Castlevania II: Simon's Quest", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d6/Castlevania_II_Box.png" },
  { name: "Castlevania III: Dracula's Curse", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fc/Castlevania_III_Box.png" },
  { name: "Contra", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2b/Contra_NES_box.png" },
  { name: "Super C", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/12/Super_C_box.png" },
  { name: "Duck Hunt", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/87/Duck_Hunt_NES_cover.png" },
  { name: "Excitebike", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f2/Excitebike_NES_box.png" },
  { name: "Punch-Out!!", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d6/PunchOutNES.jpg" },
  { name: "Dr. Mario", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/44/DrMario_NES.png" },
  { name: "Kid Icarus", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/12/KidIcarus_NES.png" },
  { name: "Balloon Fight", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2e/Balloon_Fight_NES_box.png" },
  { name: "Excitebike", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f2/Excitebike_NES_box.png" },
  { name: "Ice Climber", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/44/Ice_Climber_NES_box.png" },
  { name: "Super Mario Bros.: The Lost Levels", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6f/Super_Mario_Bros_2_JPN_box.png" },
  { name: "Ghosts 'n Goblins", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f5/GhostsN_Goblins_NES.png" },
  { name: "Adventure Island", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d3/Adventure_Island_NES_box.png" },
  { name: "Tetris", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/1b/Tetris_NES_box.png" },
  { name: "Ninja Gaiden", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/d0/Ninja_Gaiden_box.png" },
  { name: "Ninja Gaiden II: The Dark Sword of Chaos", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/d/df/Ninja_Gaiden_II_box.png" },
  { name: "Tecmo Bowl", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f4/TecmoBowl_NES_box.png" },
  { name: "River City Ransom", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/4e/River_City_Ransom_NES_cover.jpg" },
  { name: "Double Dragon", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/0b/DoubleDragon_NES_box.png" }
],
"GBA": [
  { name: "Pokémon Ruby", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/9/9d/Pokemon_Ruby_box.png" },
  { name: "Pokémon Sapphire", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/21/Pokemon_Sapphire_box.png" },
  { name: "Pokémon Emerald", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f3/Pokemon_Emerald_box.png" },
  { name: "Pokémon FireRed", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/30/Pokemon_FireRed_box.png" },
  { name: "Pokémon LeafGreen", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6f/Pokemon_LeafGreen_box.png" },
  { name: "The Legend of Zelda: The Minish Cap", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/41/Zelda_Minsh_Cap_cover.png" },
  { name: "The Legend of Zelda: A Link to the Past & Four Swords", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2b/Zelda_ALttP_FS_cover.png" },
  { name: "Metroid Fusion", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7c/Metroid_Fusion_cover.png" },
  { name: "Metroid: Zero Mission", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e4/Metroid_Zero_Mission_cover.png" },
  { name: "Castlevania: Aria of Sorrow", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/81/Castlevania_AOS_cover.png" },
  { name: "Castlevania: Harmony of Dissonance", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/43/Castlevania_HOD_cover.png" },
  { name: "Castlevania: Circle of the Moon", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/06/CotMcover.jpg" },
  { name: "Advance Wars", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/37/Advance_Wars_box.png" },
  { name: "Advance Wars 2: Black Hole Rising", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/03/Advance_Wars_2_cover.png" },
  { name: "Fire Emblem", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/4/43/Fire_Emblem_GBA_cover.png" },
  { name: "Fire Emblem: The Sacred Stones", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/f4/Fire_Emblem_The_Sacred_Stones_cover.png" },
  { name: "Mario Kart: Super Circuit", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/c/c2/Mario_Kart_Super_Circuit_box.png" },
  { name: "Mario & Luigi: Superstar Saga", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/e1/Mario_%26_Luigi_Superstar_Saga_cover.png" },
  { name: "Super Mario Advance", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/2f/Super_Mario_Advance_cover.png" },
  { name: "Super Mario Advance 2", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/38/Super_Mario_Advance_2_cover.png" },
  { name: "Super Mario Advance 3", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7a/Super_Mario_Advance_3_cover.png" },
  { name: "Super Mario Advance 4", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/7/7f/Super_Mario_Advance_4_cover.png" },
  { name: "WarioWare, Inc.: Mega Microgames!", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/1/11/WarioWare_Inc_cover.png" },
  { name: "WarioWare: Twisted!", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/f/fb/WarioWare_Twisted_cover.png" },
  { name: "Golden Sun", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/0/09/Golden_Sun_cover.png" },
  { name: "Golden Sun: The Lost Age", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/2/23/Golden_Sun_The_Lost_Age_cover.png" },
  { name: "Pokémon Mystery Dungeon: Red Rescue Team", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/8/8d/Pokemon_Mystery_Dungeon_Red_Rescue_Team_box.png" },
  { name: "Pokémon Mystery Dungeon: Blue Rescue Team", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/6/6c/Pokemon_Mystery_Dungeon_Blue_Rescue_Team_cover.png" },
  { name: "Kirby: Nightmare in Dream Land", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/e/ea/Kirby_Nightmare_in_Dream_Land_box.png" },
  { name: "Kirby & The Amazing Mirror", owned: false, img: "https://upload.wikimedia.org/wikipedia/en/3/3e/Kirby_And_The_Amazing_Mirror_cover.png" }
],
